"""init

Revision ID: bc701c1aee91
Revises: 
Create Date: 2025-06-04 20:00:06.620138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc701c1aee91'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hospital', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('review_id', sa.String(length=128), nullable=True),
    sa.Column('review_content', sa.Text(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('answer_length', sa.String(length=16), nullable=True),
    sa.Column('additional_content', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('hospital', sa.String(length=128), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=128), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('reply', sa.Text(), nullable=True),
    sa.Column('author_dtm', sa.BigInteger(), nullable=True),
    sa.Column('channel_id', sa.String(length=32), nullable=True),
    sa.Column('review_type', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('styles', 'settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('styles', 'settings',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_table('reviews')
    op.drop_table('feedback_history')
    # ### end Alembic commands ###
