"""add review_type to style, generation_event, feedback_history

Revision ID: c704a30a28aa
Revises: fa8c2d20da5a
Create Date: 2025-06-04 22:11:09.590006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c704a30a28aa'
down_revision: Union[str, None] = 'fa8c2d20da5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback_history', sa.Column('review_type', sa.String(length=16), nullable=True))
    op.add_column('generation_event', sa.Column('review_type', sa.String(length=16), nullable=True))
    op.add_column('styles', sa.Column('review_type', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('styles', 'review_type')
    op.drop_column('generation_event', 'review_type')
    op.drop_column('feedback_history', 'review_type')
    # ### end Alembic commands ###
