"""add generation_event table

Revision ID: fa8c2d20da5a
Revises: bc701c1aee91
Create Date: 2025-06-04 21:41:40.956738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa8c2d20da5a'
down_revision: Union[str, None] = 'bc701c1aee91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('hospital', sa.String(length=128), nullable=True),
    sa.Column('page_type', sa.String(length=32), nullable=True),
    sa.Column('style_name', sa.String(length=128), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generation_event')
    # ### end Alembic commands ###
